FIX Tickets #120 #122 #120
ctrl-space-labs/gendox-core pull request #149
Opened 2023-12-20 16:20 UTC by gyfantidis

- #120:
  - #122:
  - #130

**Description**:

- Fix the double split bug
- Implement the task, delete embeddings, embeddingGroup and sections when a document has updated
- update the save document file path

### Related Tickets: #120 #122 #120

2023-12-21 16:34 UTC, sekasx requested changes

2023-12-21 16:34 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/EmbeddingService.java
> +        }
embeddingRepository.deleteAll(embeddings);

2023-12-21 16:34 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/EmbeddingService.java
> +        }
Change to deleteAll

2023-12-21 16:34 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/spring/batch/jobs/splitter/steps/DocumentSplitterProcessor.java
> +        return new DocumentSectionDTO(item, fileContent, agent);
keep split here. 
save sections in the writer

2023-12-27 11:31 UTC, myrtp commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/UploadService.java
> +        UUID userId = projectAgentService.getAgentByProjectId(projectId).getUserId();
the userID can be extracted directly from the project by by getting the projectAgent and then the userID. Therefore there is no need to autowire the projectAgentService

2023-12-27 13:07 UTC, merged