Feature 35 add embeddings addapter
ctrl-space-labs/gendox-core pull request #44
Opened 2023-09-20 14:58 UTC by gyfantidis

2023-09-20 19:26 UTC, sekasx requested changes

2023-09-20 19:26 UTC, sekasx commented on database/src/main/resources/db/migrations/gendox-core/V20230917_123210__Core_Shcema_initial_tables.sql
> +
In the scripts, there is no query for:
`CREATE EXTENSION IF NOT EXISTS vector`

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +    // return DTO
delete this

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +
delete this

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                }
Dont catch the exception, exceptionHandler should handle this.
If there is any special case, that i can't think of, let's discuss it

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                return ResponseEntity.badRequest().body(response); // 400 Bad Request
through a GendoxException instead.
I am thinking that probably, you could just skip those files, without throwing any exception, lets revisit when do the refactoring.

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +
add a for loop that checks that the file extensions are 
[".txt", ".md", ...]
the actual list should come from `application.properties`
(there is a ticket describing the available file types)

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                    String fileContent = uploadService.uploadFile(file, organizationId, projectId);
Is this the actual file text? if yes, remove it. if someone upload a huge file, it will crash the whole app.

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +    public ResponseEntity<Map<String, Object>> handleFilesUpload(@RequestParam("file") List<MultipartFile> files,
Add a ticket to Refactor this with priority-3

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/converters/EmbeddingGroupConverter.java
> +public class EmbeddingGroupConverter implements GendoxConverter<EmbeddingGroup, EmbeddingGroupDTO> {
Do we use EmbeddingGroupDTO anywhere? or it's just in case?

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/EmbeddingsController.java
> +    public List<DocumentInstanceSection> findCloserSections(@RequestBody MessageDto messageDto,
why do we use MessageDto and not directly the Message entity?

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/dtos/EmbeddingGroupDTO.java
> +public class EmbeddingGroupDTO {
Why do we need `EmbeddingGroupDTO` instead of the entity `EmbeddingGroup`

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/repositories/EmbeddingGroupRepository.java
> +    @Query("SELECT eg FROM EmbeddingGroup eg WHERE eg.embeddingId = :embeddingId")
You don't need this line at all,
if you named the function `findByEmbeddingId(@Param("embeddingId") UUID embeddingId)` Spring Data is smart enough to create the query.
 
read https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/resources/application-local.yml
> +      max-request-size: 100MB
Have you tested this?

2023-09-20 19:26 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentService.java
> +    public List<DocumentInstanceSection> getProjectSections(UUID projectId) throws GendoxException {
This will have to be implemented by getAll(DocumentSectionCriteria criteria)

It's tricky, please add a ticket, assign it on me do the implementation

2023-09-21 06:58 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                return ResponseEntity.badRequest().body(response); // 400 Bad Request
I deleted the else , now if there is an empty file it just skips it

2023-09-21 06:59 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                return ResponseEntity.badRequest().body(response); // 400 Bad Request
//            else {
//                // Handle the case where the file is empty
//                response.put("error", "One or more files are empty");
//                return ResponseEntity.badRequest().body(response); // 400 Bad Request
//            }
Deleted

2023-09-21 07:11 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/converters/EmbeddingGroupConverter.java
> +public class EmbeddingGroupConverter implements GendoxConverter<EmbeddingGroup, EmbeddingGroupDTO> {
We use EmbeddingGroupDTO

2023-09-21 07:31 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/EmbeddingsController.java
> +    public List<DocumentInstanceSection> findCloserSections(@RequestBody MessageDto messageDto,
Ok I made it without using messageDTO, I haven't delete messageDTO.jave and messageConverter.java, maybe we need it in the future

2023-09-21 08:10 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/model/dtos/EmbeddingGroupDTO.java
> +public class EmbeddingGroupDTO {
Ok I made it without using `embeddingGroupDTO`, I haven't delete `embeddingGroupDTO.jave` and `embeddingGroupConverter.java`, maybe we need it in the future

2023-09-21 08:39 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/services/DocumentService.java
> +    public List<DocumentInstanceSection> getProjectSections(UUID projectId) throws GendoxException {
Create ticket #48

2023-09-21 08:48 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +    public ResponseEntity<Map<String, Object>> handleFilesUpload(@RequestParam("file") List<MultipartFile> files,
create ticket #49

2023-09-21 09:34 UTC, sekasx commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +                    String fileContent = uploadService.uploadFile(file, organizationId, projectId);
when i say remove, I mean just the `String fileContent` and the `List<String> fileContents = new ArrayList<>();`

2023-09-21 09:53 UTC, gyfantidis commented on gendox-core-api/src/main/java/dev/ctrlspace/gendox/gendoxcoreapi/controller/DocumentController.java
> +
ok but when I upload a PDF it return as a Value this 
![image](https://github.com/ctrl-space-labs/gendox-core/assets/96373640/db5600c9-9ec4-4d22-8bf3-54adf644b10c)

2023-09-21 09:58 UTC, gyfantidis commented on gendox-core-api/src/main/resources/application-local.yml
> +      max-request-size: 100MB
I tasted, It works

2023-09-21 12:20 UTC, merged